apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: timedrop
  name: timedrop
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: timedrop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: timedrop
    spec:
      containers:
      - image: ghcr.io/erock530/timedrop:1.1.4
        imagePullPolicy: Always
        name: timedrop-c
        ports:
        - containerPort: 9987
