name: Build Docker Image
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "REL_VER=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set vars
        id: vars
        run: echo "tag=${REL_VER}" >> $GITHUB_OUTPUT
      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag ghcr.io/erock530/timedrop:${{ steps.date.outputs.date }} .
      - name: Tag the Docker image
        run: docker tag ghcr.io/erock530/timedrop:${{ steps.date.outputs.date }} ghcr.io/erock530/timedrop:${{ steps.vars.outputs.tag }}
      - name: Push the Docker image to the registry
        run: docker push ghcr.io/erock530/timedrop:${{ steps.vars.outputs.tag }}#v
