on:
    workflow_dispatch:
    push:
      # Sequence of patterns matched against refs/tags
        tags:
          - 'v1*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
name: Create RPM Release

jobs:
    build:
        name: Create RPM Release ${{ github.ref_name }}
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@master
          with:
            submodules: 'true'

        - name: Set up Go 1.21
          uses: actions/setup-go@v2
          with:
            go-version: 1.21
          id: go
          
        - name: Build the RPM file
          run: "make rpm"

        - name: Release with Notes
          uses: softprops/action-gh-release@v1
          with:
            files: |
              /tmp/rpmbuild/RPMS/x86_64/timedrop*.rpm
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
